import { Attribute } from "../core/ratings";

export const ROLE_ATTRIBUTES: Record<string, Attribute[]> = {
  passer: [
    "SPEED",
    "THROWPOWER",
    "POCKETPRESENCE",
    "DECISIONMAKING",
    "SHORTACCURACY",
    "DEEPACCURACY",
  ],
  runner: ["SPEED", "SIZE", "VISION", "POWER", "PASSBLOCK"],
  catcher: [
    "SPEED",
    "SIZE",
    "ROUTERUNNING",
    "CATCHACCELERATION",
    "CATCHRADIUS",
    "RUNBLOCK",
    "VISION",
    "POWER",
  ],
  blocker: ["SPEED", "SIZE", "PASSBLOCK", "RUNBLOCK"],
  rusher: ["SPEED", "SIZE", "BLOCKSHEDDING", "BEND", "TACKLING"],
  coverer: [
    "SPEED",
    "SIZE",
    "PURSUIT",
    "MANCOVERAGE",
    "ZONECOVERAGE",
    "TACKLING",
    "BLOCKSHEDDING",
    "CATCHRADIUS",
  ],
};

export const ATTR_SHORT_LABELS: Partial<Record<Attribute, string>> = {
  SPEED: "SPD",
  SIZE: "SIZE",
  THROWPOWER: "THRP",
  POCKETPRESENCE: "PKT",
  DECISIONMAKING: "DEC",
  SHORTACCURACY: "SACC",
  DEEPACCURACY: "DACC",
  ROUTERUNNING: "RTE",
  CATCHACCELERATION: "CACC",
  CATCHRADIUS: "CRAD",
  PASSBLOCK: "PBK",
  RUNBLOCK: "RBK",
  BLOCKSHEDDING: "SHED",
  BEND: "BEND",
  MANCOVERAGE: "MAN",
  ZONECOVERAGE: "ZONE",
  TACKLING: "TAC",
  POWER: "POW",
  VISION: "VIS",
  PURSUIT: "PURS",
};

export const ATTR_LABELS: Partial<Record<Attribute, string>> = {
  SPEED: "Speed",
  SIZE: "Size",
  POCKETPRESENCE: "Pocket Pres.",
  DECISIONMAKING: "Dec. Making",
  SHORTACCURACY: "Short Acc.",
  DEEPACCURACY: "Deep Acc.",
  THROWPOWER: "Throw Power",
  VISION: "Vision",
  POWER: "Power",
  ROUTERUNNING: "Route Running",
  CATCHACCELERATION: "Catch Accel.",
  CATCHRADIUS: "Catch Radius",
  PASSBLOCK: "Pass Block",
  RUNBLOCK: "Run Block",
  BLOCKSHEDDING: "Block Shed",
  BEND: "Bend",
  MANCOVERAGE: "Man Cov.",
  ZONECOVERAGE: "Zone Cov.",
  PURSUIT: "Pursuit",
  TACKLING: "Tackling",
};
