import { Label } from "./types";

/** First and last name pools for a position. Kept separate so a player's name
 * can be built from a random first + a random (different) last, producing a
 * novel positional name rather than a real player's exact name. */
type NamePool = { first: string[]; last: string[] };

// Wide receivers — shared by both outside receiver labels (XR, ZR)
const WR: NamePool = {
  first: [
    "Jerry",
    "Randy",
    "Calvin",
    "Larry",
    "Antonio",
    "Julio",
    "Terrell",
    "Tyreek",
    "Justin",
    "Davante",
    "DeAndre",
    "Marvin",
    "Steve",
    "Andre",
    "Cooper",
    "Odell",
    "Cris",
    "Wes",
    "Michael",
    "Torry",
    "Isaac",
    "Hines",
    "Reggie",
    "Don",
    "James",
    "Brandon",
    "Keenan",
    "Stefon",
    "Mike",
    "Deebo",
    "Ja'Marr",
    "CeeDee",
  ],
  last: [
    "Rice",
    "Moss",
    "Johnson",
    "Fitzgerald",
    "Brown",
    "Jones",
    "Owens",
    "Hill",
    "Jefferson",
    "Adams",
    "Hopkins",
    "Harrison",
    "Smith",
    "Johnson",
    "Kupp",
    "Beckham",
    "Carter",
    "Welker",
    "Irvin",
    "Holt",
    "Bruce",
    "Ward",
    "Wayne",
    "Hutson",
    "Lofton",
    "Marshall",
    "Allen",
    "Diggs",
    "Evans",
    "Samuel",
    "Chase",
    "Lamb",
  ],
};

// Cornerbacks — shared by boundary corner (CB) and nickel back (NB)
const CB: NamePool = {
  first: [
    "Deion",
    "Darrelle",
    "Richard",
    "Charles",
    "Champ",
    "Jalen",
    "Patrick",
    "Stephon",
    "Aqib",
    "Chris",
    "Sauce",
    "Nnamdi",
    "Darius",
    "Marcus",
    "Joe",
    "Josh",
    "Mel",
    "Darrell",
    "Ty",
    "Mike",
    "Lester",
    "Willie",
    "Albert",
    "Everson",
    "Ronde",
    "Asante",
    "Jaire",
    "Tre'Davious",
    "Marlon",
    "Marshon",
    "Lito",
    "Antoine",
  ],
  last: [
    "Sanders",
    "Revis",
    "Sherman",
    "Woodson",
    "Bailey",
    "Ramsey",
    "Peterson",
    "Gilmore",
    "Talib",
    "Harris",
    "Gardner",
    "Asomugha",
    "Slay",
    "Peters",
    "Haden",
    "Norman",
    "Blount",
    "Green",
    "Law",
    "Haynes",
    "Hayes",
    "Brown",
    "Lewis",
    "Walls",
    "Barber",
    "Samuel",
    "Alexander",
    "White",
    "Humphrey",
    "Lattimore",
    "Sheppard",
    "Winfield",
  ],
};

/** First/last name pools keyed by the in-game player label. */
export const NAME_POOLS: Record<Label, NamePool> = {
  QB: {
    first: [
      "Tom",
      "Patrick",
      "Peyton",
      "Aaron",
      "Drew",
      "Ben",
      "Joe",
      "Brett",
      "Dan",
      "John",
      "Steve",
      "Kurt",
      "Russell",
      "Lamar",
      "Warren",
      "Matt",
    ],
    last: [
      "Brady",
      "Mahomes",
      "Manning",
      "Rodgers",
      "Brees",
      "Roethlisberger",
      "Montana",
      "Favre",
      "Marino",
      "Elway",
      "Young",
      "Warner",
      "Wilson",
      "Jackson",
      "Moon",
      "Ryan",
    ],
  },
  RB: {
    first: [
      "Adrian",
      "LaDainian",
      "Marshawn",
      "Derrick",
      "Emmitt",
      "Barry",
      "Christian",
      "Frank",
      "Walter",
      "Marshall",
      "Edgerrin",
      "Saquon",
      "Le'Veon",
      "Jamaal",
      "Todd",
      "Alvin",
    ],
    last: [
      "Peterson",
      "Tomlinson",
      "Lynch",
      "Henry",
      "Smith",
      "Sanders",
      "McCaffrey",
      "Gore",
      "Payton",
      "Faulk",
      "James",
      "Barkley",
      "Bell",
      "Charles",
      "Gurley",
      "Kamara",
    ],
  },
  TE: {
    first: [
      "Rob",
      "Travis",
      "Antonio",
      "Tony",
      "Jason",
      "Jimmy",
      "Greg",
      "George",
      "Shannon",
      "Kellen",
      "Dallas",
      "Mark",
      "Zach",
      "Kyle",
      "Ozzie",
      "Vernon",
    ],
    last: [
      "Gronkowski",
      "Kelce",
      "Gates",
      "Gonzalez",
      "Witten",
      "Graham",
      "Olsen",
      "Kittle",
      "Sharpe",
      "Winslow",
      "Clark",
      "Andrews",
      "Ertz",
      "Pitts",
      "Newsome",
      "Davis",
    ],
  },
  LT: {
    first: [
      "Joe",
      "Trent",
      "Tyron",
      "Quenton",
      "Jonathan",
      "Walter",
      "Steve",
      "Anthony",
      "Orlando",
      "Willie",
      "Andrew",
      "Laremy",
      "Ron",
      "Gary",
      "Tony",
      "David",
    ],
    last: [
      "Thomas",
      "Williams",
      "Smith",
      "Nelson",
      "Ogden",
      "Jones",
      "Hutchinson",
      "Muñoz",
      "Pace",
      "Roaf",
      "Whitworth",
      "Tunsil",
      "Yary",
      "Zimmerman",
      "Boselli",
      "Bakhtiari",
    ],
  },
  C: {
    first: [
      "Jason",
      "Maurkice",
      "Travis",
      "Nick",
      "Alex",
      "Rodney",
      "Jeff",
      "Creed",
      "Mike",
      "Dermontti",
      "Dwight",
      "Ryan",
      "Corey",
      "Olin",
      "Frank",
      "Tom",
    ],
    last: [
      "Kelce",
      "Pouncey",
      "Frederick",
      "Mangold",
      "Mack",
      "Hudson",
      "Saturday",
      "Humphrey",
      "Webster",
      "Dawson",
      "Stephenson",
      "Kalil",
      "Linsley",
      "Kreutz",
      "Ragnow",
      "Nalen",
    ],
  },
  RT: {
    first: [
      "Zack",
      "Lane",
      "Marshal",
      "Jahri",
      "David",
      "Mitchell",
      "Brandon",
      "Larry",
      "Penei",
      "Tristan",
      "Ryan",
      "Erik",
      "Jon",
      "Taylor",
      "Morgan",
      "Marcus",
    ],
    last: [
      "Martin",
      "Johnson",
      "Yanda",
      "Evans",
      "DeCastro",
      "Schwartz",
      "Brooks",
      "Allen",
      "Sewell",
      "Wirfs",
      "Ramczyk",
      "Williams",
      "Runyan",
      "Lewan",
      "Moses",
      "Gilbert",
    ],
  },
  LE: {
    first: [
      "J.J.",
      "T.J.",
      "Khalil",
      "Von",
      "Reggie",
      "Michael",
      "Julius",
      "Maxx",
      "Cameron",
      "Danielle",
      "Aidan",
      "Joey",
      "Chris",
      "Robert",
      "Howie",
      "Brandon",
    ],
    last: [
      "Watt",
      "Watt",
      "Mack",
      "Miller",
      "White",
      "Strahan",
      "Peppers",
      "Crosby",
      "Jordan",
      "Hunter",
      "Hutchinson",
      "Bosa",
      "Long",
      "Mathis",
      "Long",
      "Graham",
    ],
  },
  DT: {
    first: [
      "Aaron",
      "Chris",
      "Fletcher",
      "Ndamukong",
      "Geno",
      "Vince",
      "Gerald",
      "Warren",
      "John",
      "Cortez",
      "Quinnen",
      "Dexter",
      "DeForest",
      "Jeffery",
      "Cam",
      "Alan",
    ],
    last: [
      "Donald",
      "Jones",
      "Cox",
      "Suh",
      "Atkins",
      "Wilfork",
      "McCoy",
      "Sapp",
      "Randle",
      "Kennedy",
      "Williams",
      "Lawrence",
      "Buckner",
      "Simmons",
      "Heyward",
      "Page",
    ],
  },
  RE: {
    first: [
      "Myles",
      "Nick",
      "DeMarcus",
      "Lawrence",
      "Bruce",
      "Jared",
      "Chandler",
      "Justin",
      "Jason",
      "Robert",
      "Trey",
      "Brian",
      "Everson",
      "Yannick",
      "Olivier",
      "Alex",
    ],
    last: [
      "Garrett",
      "Bosa",
      "Ware",
      "Taylor",
      "Smith",
      "Allen",
      "Jones",
      "Houston",
      "Pierre-Paul",
      "Quinn",
      "Hendrickson",
      "Burns",
      "Griffen",
      "Ngakoue",
      "Vernon",
      "Highsmith",
    ],
  },
  LB: {
    first: [
      "Ray",
      "Luke",
      "Bobby",
      "Patrick",
      "Brian",
      "Fred",
      "Lavonte",
      "NaVorro",
      "Derrick",
      "Micah",
      "Roquan",
      "Demario",
      "C.J.",
      "Shaquille",
      "Tremaine",
      "Matt",
    ],
    last: [
      "Lewis",
      "Kuechly",
      "Wagner",
      "Willis",
      "Urlacher",
      "Warner",
      "David",
      "Bowman",
      "Brooks",
      "Parsons",
      "Smith",
      "Davis",
      "Mosley",
      "Leonard",
      "Edmunds",
      "Milano",
    ],
  },
  FS: {
    first: [
      "Ed",
      "Earl",
      "Tyrann",
      "Minkah",
      "Eric",
      "Devin",
      "Sean",
      "Justin",
      "Kevin",
      "Jessie",
      "Marcus",
      "Micah",
      "Malik",
      "Ha Ha",
      "Glover",
      "Tashaun",
    ],
    last: [
      "Reed",
      "Thomas",
      "Mathieu",
      "Fitzpatrick",
      "Weddle",
      "McCourty",
      "Taylor",
      "Simmons",
      "Byard",
      "Bates",
      "Williams",
      "Hyde",
      "Hooker",
      "Clinton-Dix",
      "Quin",
      "Gipson",
    ],
  },
  SS: {
    first: [
      "Troy",
      "Kam",
      "Harrison",
      "Jamal",
      "Derwin",
      "Budda",
      "Landon",
      "Malcolm",
      "Adrian",
      "Jordan",
      "Kyle",
      "T.J.",
      "Reshad",
      "Vonn",
      "Tony",
      "Ronnie",
    ],
    last: [
      "Polamalu",
      "Chancellor",
      "Smith",
      "Adams",
      "James",
      "Baker",
      "Collins",
      "Jenkins",
      "Amos",
      "Poyer",
      "Hamilton",
      "Ward",
      "Jones",
      "Bell",
      "Jefferson",
      "Lott",
    ],
  },
  XR: WR,
  ZR: WR,
  CB: CB,
  NB: CB,
};

/** Builds a positional name: a random first name paired with a last name from a
 * different entry (so it never reproduces a real player's exact name). */
export function generatePlayerName(label: Label): string {
  const pool = NAME_POOLS[label];
  const firstIdx = Math.floor(Math.random() * pool.first.length);

  let lastIdx = Math.floor(Math.random() * pool.last.length);
  while (pool.last.length > 1 && lastIdx === firstIdx) {
    lastIdx = Math.floor(Math.random() * pool.last.length);
  }

  return `${pool.first[firstIdx]} ${pool.last[lastIdx]}`;
}
